[package]
name = "chat"
version = "0.1.0"
authors = ["gla9931 <jarredglaser@northwesternmutual.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "*"
log = "0.4.14"
env_logger = "0.9.0"