CREATE TABLE user (
    user_id INTEGER PRIMARY KEY,
    username TEXT,
    password TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE item (
    item_id INTEGER PRIMARY KEY,
    user_id INTEGER REFERENCES user(user_id),
    name TEXT,
    category TEXT,
    is_checked BOOL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);